import 'package:xinput_gamepad/src/enums/keyboard_key.dart';

class KeyboardKeyEnumConverter {
  static int? convertKeyboardKey(KeyboardKey keyCode) {
    switch (keyCode) {
      case KeyboardKey.A:
        return 65;
      case KeyboardKey.ADD:
        return 107;
      case KeyboardKey.ALT:
        return 18;
      case KeyboardKey.APPS:
        return 93;
      case KeyboardKey.ATTN:
        return 246;
      case KeyboardKey.B:
        return 66;
      case KeyboardKey.BACKSPACE:
        return 8;
      case KeyboardKey.BROWSER_BACK:
        return 166;
      case KeyboardKey.BROWSER_FAVORITES:
        return 171;
      case KeyboardKey.BROWSER_FORAWRD:
        return 167;
      case KeyboardKey.BROWSER_HOME:
        return 172;
      case KeyboardKey.BROWSER_REFRESH:
        return 168;
      case KeyboardKey.BROWSER_SEARCH:
        return 170;
      case KeyboardKey.BROWSER_STOP:
        return 169;
      case KeyboardKey.C:
        return 67;
      case KeyboardKey.CANCEL:
        return 3;
      case KeyboardKey.CAPS_LOCK:
        return 20;
      case KeyboardKey.CONTROL:
        return 17;
      case KeyboardKey.CRSEL:
        return 247;
      case KeyboardKey.D:
        return 68;
      case KeyboardKey.D0:
        return 48;
      case KeyboardKey.D1:
        return 49;
      case KeyboardKey.D2:
        return 50;
      case KeyboardKey.D3:
        return 51;
      case KeyboardKey.D4:
        return 52;
      case KeyboardKey.D5:
        return 53;
      case KeyboardKey.D6:
        return 54;
      case KeyboardKey.D7:
        return 55;
      case KeyboardKey.D8:
        return 56;
      case KeyboardKey.D9:
        return 57;
      case KeyboardKey.DECIMAL:
        return 110;
      case KeyboardKey.DELETE:
        return 46;
      case KeyboardKey.DIVIDE:
        return 111;
      case KeyboardKey.DOWN_ARROW:
        return 40;
      case KeyboardKey.E:
        return 69;
      case KeyboardKey.END:
        return 35;
      case KeyboardKey.ENTER:
        return 13;
      case KeyboardKey.ERASE_EOF:
        return 249;
      case KeyboardKey.EXECUTE:
        return 43;
      case KeyboardKey.EXSEL:
        return 248;
      case KeyboardKey.F:
        return 70;
      case KeyboardKey.F1:
        return 112;
      case KeyboardKey.F2:
        return 113;
      case KeyboardKey.F3:
        return 114;
      case KeyboardKey.F4:
        return 115;
      case KeyboardKey.F5:
        return 116;
      case KeyboardKey.F6:
        return 117;
      case KeyboardKey.F7:
        return 118;
      case KeyboardKey.F8:
        return 119;
      case KeyboardKey.F9:
        return 120;
      case KeyboardKey.F10:
        return 121;
      case KeyboardKey.F11:
        return 122;
      case KeyboardKey.F12:
        return 123;
      case KeyboardKey.F13:
        return 124;
      case KeyboardKey.F14:
        return 125;
      case KeyboardKey.F15:
        return 126;
      case KeyboardKey.F16:
        return 127;
      case KeyboardKey.F17:
        return 128;
      case KeyboardKey.F18:
        return 129;
      case KeyboardKey.F19:
        return 130;
      case KeyboardKey.F20:
        return 131;
      case KeyboardKey.F21:
        return 132;
      case KeyboardKey.F22:
        return 133;
      case KeyboardKey.F23:
        return 134;
      case KeyboardKey.F24:
        return 135;
      case KeyboardKey.G:
        return 71;
      case KeyboardKey.H:
        return 72;
      case KeyboardKey.HELP:
        return 47;
      case KeyboardKey.HOME:
        return 36;
      case KeyboardKey.I:
        return 73;
      case KeyboardKey.INSERT:
        return 45;
      case KeyboardKey.J:
        return 74;
      case KeyboardKey.K:
        return 75;
      case KeyboardKey.L:
        return 76;
      case KeyboardKey.LAUNCH_APP_1:
        return 182;
      case KeyboardKey.LAUNCH_APP_2:
        return 183;
      case KeyboardKey.LAUNCH_MAIL:
        return 180;
      case KeyboardKey.L_CTRL:
        return 162;
      case KeyboardKey.LEFT_ARROW:
        return 37;
      case KeyboardKey.L_ALT:
        return 164;
      case KeyboardKey.L_SHIFT:
        return 160;
      case KeyboardKey.L_WIN:
        return 91;
      case KeyboardKey.M:
        return 77;
      case KeyboardKey.MEDIA_NEXT_TRACK:
        return 176;
      case KeyboardKey.MEDIA_PLAY_PAUSE:
        return 179;
      case KeyboardKey.MEDIA_PREVIOUS_TRACK:
        return 177;
      case KeyboardKey.MEDIA_STOP:
        return 178;
      case KeyboardKey.MULTIPLY:
        return 106;
      case KeyboardKey.N:
        return 78;
      case KeyboardKey.NUM_LOCK:
        return 144;
      case KeyboardKey.NUM_PAD_0:
        return 96;
      case KeyboardKey.NUM_PAD_1:
        return 97;
      case KeyboardKey.NUM_PAD_2:
        return 98;
      case KeyboardKey.NUM_PAD_3:
        return 99;
      case KeyboardKey.NUM_PAD_4:
        return 100;
      case KeyboardKey.NUM_PAD_5:
        return 101;
      case KeyboardKey.NUM_PAD_6:
        return 102;
      case KeyboardKey.NUM_PAD_7:
        return 103;
      case KeyboardKey.NUM_PAD_8:
        return 104;
      case KeyboardKey.NUM_PAD_9:
        return 105;
      case KeyboardKey.O:
        return 79;
      case KeyboardKey.OEM_1:
        return 186;
      case KeyboardKey.OEM_2:
        return 191;
      case KeyboardKey.OEM_3:
        return 192;
      case KeyboardKey.OEM_4:
        return 219;
      case KeyboardKey.OEM_5:
        return 220;
      case KeyboardKey.OEM_6:
        return 221;
      case KeyboardKey.OEM_7:
        return 222;
      case KeyboardKey.OEM_8:
        return 223;
      case KeyboardKey.OEM_CLEAR:
        return 254;
      case KeyboardKey.OEM_COMMA:
        return 188;
      case KeyboardKey.OEM_MINUS:
        return 189;
      case KeyboardKey.OEM_PERIOD:
        return 190;
      case KeyboardKey.OEM_PLUS:
        return 187;
      case KeyboardKey.P:
        return 80;
      case KeyboardKey.PA_1:
        return 253;
      case KeyboardKey.PAGE_DOWN:
        return 34;
      case KeyboardKey.PAGE_UP:
        return 33;
      case KeyboardKey.PAUSE:
        return 19;
      case KeyboardKey.PALY:
        return 250;
      case KeyboardKey.PRINT:
        return 42;
      case KeyboardKey.PRINT_SCREEN:
        return 44;
      case KeyboardKey.PROCESS_KEY:
        return 229;
      case KeyboardKey.Q:
        return 81;
      case KeyboardKey.R:
        return 82;
      case KeyboardKey.R_CTRL:
        return 163;
      case KeyboardKey.RETURN:
        return 355;
      case KeyboardKey.RIGHT_ARROW:
        return 39;
      case KeyboardKey.R_ALT:
        return 165;
      case KeyboardKey.R_SHIFT:
        return 161;
      case KeyboardKey.R_WIN:
        return 92;
      case KeyboardKey.S:
        return 83;
      case KeyboardKey.SCROLL_LOCK:
        return 145;
      case KeyboardKey.SELECT:
        return 41;
      case KeyboardKey.SELECT_MEDIA:
        return 181;
      case KeyboardKey.SEPARATOR:
        return 108;
      case KeyboardKey.SHIFT:
        return 16;
      case KeyboardKey.SLEEP:
        return 95;
      case KeyboardKey.SPACE:
        return 32;
      case KeyboardKey.SUBTRACT:
        return 109;
      case KeyboardKey.T:
        return 84;
      case KeyboardKey.TAB:
        return 9;
      case KeyboardKey.U:
        return 85;
      case KeyboardKey.UP_ARROW:
        return 38;
      case KeyboardKey.V:
        return 86;
      case KeyboardKey.VOLUME_DOWN:
        return 174;
      case KeyboardKey.VOLUME_MUTE:
        return 173;
      case KeyboardKey.VOLUME_UP:
        return 175;
      case KeyboardKey.W:
        return 87;
      case KeyboardKey.X:
        return 88;
      case KeyboardKey.Y:
        return 89;
      case KeyboardKey.Z:
        return 90;
      case KeyboardKey.ZOOM:
        return 251;
      default:
        return null;
    }
  }
}
